# Generated by Django 3.2.3 on 2021-05-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=1000)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
